# -*- coding: utf-8 -*-
"""PGM1 KNN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A71W_Ijwe54oJZdSJwZSVt9GbX94tLw4
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

data=pd.read_csv('iris.csv')
data.head()

x=data.iloc[:,:4]
x.head()

y=data.iloc[:,-1]
y.head()

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.20)

x_train.head()

x_test.head()

classifier=KNeighborsClassifier(n_neighbors=5)

classifier.fit(x_train,y_train)

y_pred=classifier.predict(x_test)

y_pred

y_test

from sklearn.metrics import classification_report, confusion_matrix,accuracy_score

result=confusion_matrix(y_test,y_pred)
print("Confusion Matrix:")
print(result)

result1=classification_report(y_test,y_pred)
print("Classification Report:")
print(result1)

result2=accuracy_score(y_test,y_pred)
print("Accuracy:",result2)
print(result2)